export interface ProductInfo {
  slug: string;
  title: string;
  short: string;
  description: string;
  inputLabel: string;
  inputExample: string;
  outputs: string[];
  features: string[];
  category: string;
  basePriceKes: number;
  vatExclusive: boolean;
  requiresFileUpload: boolean;
  fileTypes: string[];
  cbConsentRequired: boolean;
}

export const PRODUCTS: ProductInfo[] = [
  // Identity — Standard
  {
    slug: 'iprs-standard',
    title: 'IPRS Standard Verification',
    short: 'Instant National ID validation against the government registry.',
    description:
      'Confirm that customers are who they say they are by validating their National ID against the Integrated Population Registration System in real time.',
    inputLabel: 'National ID Number',
    inputExample: '12345678',
    outputs: [
      'Full Name',
      'Date of Birth',
      'Gender',
      'Serial Number',
      'Place of Birth',
      'Citizenship',
      'Alive Status',
    ],
    features: [
      'Real-time verification against IPRS records',
      'Instant name and ID validation',
      'Serial number verification',
      'Government-backed accuracy',
    ],
    category: 'Identity — Standard',
    basePriceKes: 30,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  {
    slug: 'match-id-phone',
    title: 'Match ID & Phone Number',
    short: 'Cross-verify National ID and phone ownership in one check.',
    description:
      'Validate that a National ID and phone number belong to the same person — essential for KYC and fraud prevention.',
    inputLabel: 'National ID Number & Phone Number',
    inputExample: 'ID: 12345678, Phone: 0712345678',
    outputs: ['ID Number', 'Phone Number', 'Match Result', 'Owner Name'],
    features: [
      'Real-time cross-validation',
      'Fraud prevention for OTP/mobile flows',
      'Single check for dual verification',
      'Owner name confirmation',
    ],
    category: 'Identity — Standard',
    basePriceKes: 30,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  {
    slug: 'employer-verification',
    title: 'Employer Verification',
    short: 'Confirm employment status and current employer.',
    description:
      'Verify that a customer works at the claimed organization — critical for income verification and loan affordability.',
    inputLabel: 'National ID Number & Employer Name',
    inputExample: 'ID: 12345678, Employer: Safaricom PLC',
    outputs: ['ID Number', 'Employer Name', 'Current Employer', 'Employment Status'],
    features: [
      'Real-time employer validation',
      'Current vs past employment',
      'Employment status confirmation',
      'Income verification support',
    ],
    category: 'Identity — Standard',
    basePriceKes: 30,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  {
    slug: 'face-id-match',
    title: 'Face ID Match',
    short: 'Biometric face matching against ID photo.',
    description:
      'Compare a live selfie or uploaded photo against the government ID photo for high-assurance identity verification.',
    inputLabel: 'National ID Number & Face Image (Base64)',
    inputExample: 'ID: 12345678, Face: [base64]',
    outputs: ['ID Number', 'Match Score', 'Matched (Yes/No)', 'Reference Image'],
    features: [
      'Biometric face matching',
      'Match score (0-100%)',
      'Liveness-ready',
      'High-assurance KYC',
    ],
    category: 'Identity — Standard',
    basePriceKes: 30,
    vatExclusive: true,
    requiresFileUpload: true,
    fileTypes: ['image/jpeg', 'image/png'],
    cbConsentRequired: false,
  },
  {
    slug: 'bank-account-verification',
    title: 'Bank Account Verification',
    short: 'Validate bank account ownership and status.',
    description:
      'Confirm that a bank account belongs to your customer and check its active status before disbursements.',
    inputLabel: 'Account Number, Bank Code & National ID',
    inputExample: 'Account: 0123456789, Bank: 01 (KCB), ID: 12345678',
    outputs: ['Account Number', 'Bank Name', 'Account Name', 'Account Status', 'ID Match'],
    features: [
      'Account ownership verification',
      'Active/dormant/closed status',
      'ID number cross-match',
      'Pre-disbursement validation',
    ],
    category: 'Identity — Standard',
    basePriceKes: 30,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  // Identity — Premium
  {
    slug: 'alien-id',
    title: 'Alien ID Verification',
    short: "Validate foreign nationals' Alien IDs.",
    description: 'Verify the authenticity and status of Alien IDs for foreign national customers.',
    inputLabel: 'Alien ID',
    inputExample: 'ALN1234567',
    outputs: ['Alien ID', 'Full Name', 'Nationality', 'DOB', 'Gender', 'Expiry Date', 'Status'],
    features: [
      'Alien ID authenticity',
      'Expiry date check',
      'Nationality verification',
      'Foreign national KYC',
    ],
    category: 'Identity — Premium',
    basePriceKes: 75,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  {
    slug: 'aml-pep-screen',
    title: 'AML & PEP Screen',
    short: 'Anti-Money Laundering and Politically Exposed Person screening.',
    description:
      'Screen customers against global sanctions, watchlists, and PEP databases for compliance.',
    inputLabel: 'National ID Number',
    inputExample: '12345678',
    outputs: [
      'ID Number',
      'Full Name',
      'AML Match',
      'PEP Match',
      'Watchlist Matches',
      'Risk Level',
    ],
    features: [
      'Global sanctions screening',
      'PEP detection',
      'Watchlist monitoring',
      'Risk classification (Low/Medium/High/Critical)',
    ],
    category: 'Identity — Premium',
    basePriceKes: 75,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  {
    slug: 'passport-check',
    title: 'Passport Check',
    short: 'Validate passport authenticity and details.',
    description: 'Verify international passport details for cross-border customers.',
    inputLabel: 'Passport Number & Nationality',
    inputExample: 'Passport: A1234567, Nationality: Kenyan',
    outputs: [
      'Passport Number',
      'Nationality',
      'Full Name',
      'DOB',
      'Gender',
      'Expiry Date',
      'Issuing Country',
      'Status',
    ],
    features: [
      'Passport authenticity',
      'Expiry validation',
      'Issuing country verification',
      'Cross-border KYC',
    ],
    category: 'Identity — Premium',
    basePriceKes: 75,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  // Utility
  {
    slug: 'sim-swap-check',
    title: 'SIM Swap Check',
    short: 'Detect recent SIM changes before fraud happens.',
    description:
      'Protect OTP and mobile-money flows from SIM-swap fraud with real-time swap detection and risk scoring.',
    inputLabel: 'Phone Number',
    inputExample: '+254712345678',
    outputs: ['Phone Number', 'Last Swap Date', 'Days Since Swap', 'Risk Level'],
    features: [
      'Real-time SIM swap detection',
      'Historical swap tracking',
      'Risk level classification (Low/Medium/High)',
      'Pre-disbursement fraud guard',
    ],
    category: 'Utility',
    basePriceKes: 20,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  {
    slug: 'kplc-location-checker',
    title: 'KPLC Location Checker',
    short: 'Verify customer address via KPLC meter records.',
    description:
      "Confirm a customer's physical address using Kenya Power meter records for address verification.",
    inputLabel: 'KPLC Meter Number',
    inputExample: '12345678',
    outputs: ['Meter Number', 'Account Number', 'Customer Name', 'Location', 'Status'],
    features: [
      'Address verification via utility records',
      'Active/inactive/disconnected status',
      'Physical location confirmation',
      'KYC address validation',
    ],
    category: 'Utility',
    basePriceKes: 20,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  {
    slug: 'kra-pin-verification',
    title: 'KRA PIN Verification',
    short: 'Validate KRA PINs and tax compliance status.',
    description:
      "Verify the authenticity of a customer's KRA PIN and check their tax registration status before onboarding or disbursing loans.",
    inputLabel: 'KRA PIN or National ID',
    inputExample: 'A012345678Z or 12345678',
    outputs: ['KRA PIN', 'Taxpayer Name', 'Status', 'Tax Obligation'],
    features: [
      'KRA PIN validation and authenticity check',
      'Tax compliance status (Active/Inactive/Deregistered)',
      'Works with ID number as fallback lookup',
      'Registration status confirmation',
    ],
    category: 'Utility',
    basePriceKes: 20,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  {
    slug: 'search-name-by-phone',
    title: 'Search Name by Phone Number',
    short: 'Find the registered owner of a phone number.',
    description: 'Retrieve the registered owner name and ID for a given phone number.',
    inputLabel: 'Phone Number',
    inputExample: '0712345678',
    outputs: ['Phone Number', 'Owner Name', 'ID Number'],
    features: [
      'Owner name retrieval',
      'ID number cross-reference',
      'Single number lookup',
      'Fast phone KYC',
    ],
    category: 'Utility',
    basePriceKes: 20,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  // Identity & CRB
  {
    slug: 'search-phones-by-id',
    title: 'Search Phone Numbers by ID',
    short: 'Find all phone numbers registered to a National ID.',
    description:
      "Retrieve all phone numbers linked to a customer's National ID for comprehensive contact verification.",
    inputLabel: 'National ID Number',
    inputExample: '12345678',
    outputs: ['ID Number', 'Registered Numbers', 'Primary Number'],
    features: [
      'All linked numbers retrieval',
      'Primary number identification',
      'Comprehensive contact verification',
      'Fraud pattern detection',
    ],
    category: 'Identity & CRB',
    basePriceKes: 50,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: false,
  },
  // Vehicle
  {
    slug: 'motor-vehicle-ownership',
    title: 'Motor Vehicle Ownership',
    short: 'Verify vehicle ownership and registration details.',
    description:
      'Confirm vehicle ownership, registration status, and logbook details for asset-backed lending.',
    inputLabel: 'Vehicle Registration Number',
    inputExample: 'KCA 123A',
    outputs: [
      'Registration Number',
      'Owner ID',
      'Owner Name',
      'Make',
      'Model',
      'Year',
      'Color',
      'Engine Number',
      'Chassis Number',
      'Logbook Status',
    ],
    features: [
      'Vehicle ownership verification',
      'Registration status (Valid/Expired/Cancelled)',
      'Full vehicle specifications',
      'Asset-backed lending support',
    ],
    category: 'Vehicle',
    basePriceKes: 1160,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: true,
  },
  {
    slug: 'drivers-license-verification',
    title: "Driver's License Verification",
    short: "Validate driver's license authenticity and status.",
    description: "Verify driver's license details including class, issue/expiry dates, and status.",
    inputLabel: "Driver's License Number",
    inputExample: 'DL1234567',
    outputs: [
      'DL Number',
      'ID Number',
      'Full Name',
      'DOB',
      'License Class',
      'Issue Date',
      'Expiry Date',
      'Status',
    ],
    features: [
      'License authenticity',
      'Class verification',
      'Expiry date check',
      'Status (Valid/Expired/Suspended/Revoked)',
    ],
    category: 'Vehicle',
    basePriceKes: 200,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: true,
  },
  // Credit Reference — Metropol
  {
    slug: 'metropol-score-only',
    title: 'Metropol Score Only',
    short: 'Credit score from Metropol CRB.',
    description: 'Quick creditworthiness assessment with Metropol score and risk band.',
    inputLabel: 'National ID Number',
    inputExample: '12345678',
    outputs: ['Score (300-850)', 'Score Band', 'Risk Level'],
    features: [
      'Metropol credit score',
      'Score band classification',
      'Risk level (Low/Medium/High)',
      'Quick pre-screening',
    ],
    category: 'Credit Reference — Metropol',
    basePriceKes: 85,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: true,
  },
  {
    slug: 'metropol-standard-report',
    title: 'Metropol Standard Report',
    short: 'Standard credit report from Metropol CRB.',
    description: 'Comprehensive credit report with account summary and payment history.',
    inputLabel: 'National ID Number',
    inputExample: '12345678',
    outputs: ['Score', 'Score Band', 'Accounts Summary', 'Payment History'],
    features: [
      'Full credit score',
      'Account summary (total/active/closed/defaulted)',
      'Payment history per account',
      'Creditworthiness assessment',
    ],
    category: 'Credit Reference — Metropol',
    basePriceKes: 150,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: true,
  },
  {
    slug: 'metropol-full-report',
    title: 'Metropol Full Report',
    short: 'Complete credit report from Metropol CRB.',
    description: 'Full credit bureau report with all accounts, inquiries, and public records.',
    inputLabel: 'National ID Number',
    inputExample: '12345678',
    outputs: ['Score', 'Identity', 'All Accounts', 'Inquiries', 'Public Records'],
    features: [
      'Complete credit profile',
      'All accounts with balances and history',
      'Credit inquiries log',
      'Public records (judgments, etc.)',
    ],
    category: 'Credit Reference — Metropol',
    basePriceKes: 300,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: true,
  },
  // Credit Reference — CreditInfo
  {
    slug: 'creditinfo-score-only',
    title: 'CreditInfo Score Only',
    short: 'Credit score from CreditInfo CRB.',
    description: 'Quick creditworthiness assessment with CreditInfo score.',
    inputLabel: 'National ID Number',
    inputExample: '12345678',
    outputs: ['Score', 'Score Band', 'Risk Level'],
    features: [
      'CreditInfo credit score',
      'Score band classification',
      'Risk level assessment',
      'Alternative bureau score',
    ],
    category: 'Credit Reference — CreditInfo',
    basePriceKes: 50,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: true,
  },
  {
    slug: 'creditinfo-comprehensive',
    title: 'CreditInfo Comprehensive Report',
    short: 'Comprehensive credit report from CreditInfo CRB.',
    description: 'Full credit report with accounts, guarantees, and repayment history.',
    inputLabel: 'National ID Number',
    inputExample: '12345678',
    outputs: ['Score', 'Identity', 'Credit Accounts', 'Guarantees'],
    features: [
      'Complete credit profile',
      'All credit accounts with limits and balances',
      'Guarantees and co-signed loans',
      '12-month repayment history',
    ],
    category: 'Credit Reference — CreditInfo',
    basePriceKes: 350,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: true,
  },
  {
    slug: 'creditinfo-crb-status',
    title: 'CreditInfo CRB Status',
    short: 'CRB listing status from CreditInfo.',
    description: 'Check if a customer is listed, clear, or on watchlist with CreditInfo.',
    inputLabel: 'National ID Number',
    inputExample: '12345678',
    outputs: ['Status (Clear/Listed/Watchlist)', 'Listing Details'],
    features: [
      'CRB listing status',
      'Outstanding amounts and dates',
      'Lender details for listings',
      'Clearance certificate support',
    ],
    category: 'Credit Reference — CreditInfo',
    basePriceKes: 2000,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: true,
  },
  // KYB
  {
    slug: 'brs',
    title: 'BRS (Business Registration)',
    short: 'Business Registration Services company verification.',
    description:
      'Verify business registration, directors, shareholders, and status via the Business Registration Service.',
    inputLabel: 'Business Registration Number',
    inputExample: 'PVT-RSTU123',
    outputs: [
      'Business Name',
      'Reg Number',
      'Registration Date',
      'Status',
      'Directors',
      'Shareholders',
      'Address',
      'Business Type',
    ],
    features: [
      'Business registration verification',
      'Director and shareholder details',
      'Registration date and status',
      'KYB compliance',
    ],
    category: 'KYB',
    basePriceKes: 1300,
    vatExclusive: true,
    requiresFileUpload: true,
    fileTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    cbConsentRequired: true,
  },
  // Analytics
  {
    slug: 'spin-score-only',
    title: 'SPIN Score Only',
    short: 'SPIN Mobile credit score with factor analysis.',
    description:
      'Proprietary credit score (1-100) with detailed factor breakdown for lending decisions.',
    inputLabel: 'National ID Number',
    inputExample: '12345678',
    outputs: ['Score (1-100)', 'Score Band', 'Risk Level', 'Factor Analysis'],
    features: [
      'Proprietary SPIN score',
      '5-factor analysis (Payment, Utilization, Age, Mix, Inquiries)',
      'Risk level classification',
      'Lending decision support',
    ],
    category: 'Analytics',
    basePriceKes: 130,
    vatExclusive: true,
    requiresFileUpload: false,
    fileTypes: [],
    cbConsentRequired: true,
  },
  {
    slug: 'scanned-statement',
    title: 'Scanned Statement Analysis',
    short: 'AI-powered bank/M-Pesa statement analysis.',
    description:
      'Upload scanned PDF statements for automated transaction extraction, categorization, and financial health scoring.',
    inputLabel: 'Statement Pages & File (Base64)',
    inputExample: 'Pages: 12, File: [base64 PDF]',
    outputs: ['Pages Processed', 'Transactions', 'Summary (Credits/Debits/Balances)'],
    features: [
      'AI-powered OCR extraction',
      'Transaction categorization',
      'Income/expense analysis',
      'Financial health scoring',
      'Pricing: KES 120 + KES 4/page',
    ],
    category: 'Analytics',
    basePriceKes: 120,
    vatExclusive: true,
    requiresFileUpload: true,
    fileTypes: ['application/pdf', 'image/jpeg', 'image/png'],
    cbConsentRequired: false,
  },
];

export const PRODUCT_CATEGORIES = [
  'Identity — Standard',
  'Identity — Premium',
  'Utility',
  'Identity & CRB',
  'Vehicle',
  'Credit Reference — Metropol',
  'Credit Reference — CreditInfo',
  'KYB',
  'Analytics',
];

export function getProductsByCategory(category: string): ProductInfo[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getProductBySlug(slug: string): ProductInfo | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}
